// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: grpc/files.proto

package filepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Filesize      int64                  `protobuf:"varint,2,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Mimetype      string                 `protobuf:"bytes,3,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_grpc_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_grpc_files_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadMetadata) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *UploadMetadata) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *UploadMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_grpc_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_grpc_files_proto_rawDescGZIP(), []int{1}
}

func (x *UploadChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadRequest_Metadata
	//	*UploadRequest_Chunk
	Data          isUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_grpc_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_files_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRequest) GetData() isUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() *UploadChunk {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Data interface {
	isUploadRequest_Data()
}

type UploadRequest_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk *UploadChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Metadata) isUploadRequest_Data() {}

func (*UploadRequest_Chunk) isUploadRequest_Data() {}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Filesize      int64                  `protobuf:"varint,3,opt,name=filesize,proto3" json:"filesize,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_grpc_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_files_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadResponse) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *UploadResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_grpc_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_files_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Part          int64                  `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_grpc_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_grpc_files_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DownloadChunk) GetPart() int64 {
	if x != nil {
		return x.Part
	}
	return 0
}

var File_grpc_files_proto protoreflect.FileDescriptor

const file_grpc_files_proto_rawDesc = "" +
	"\n" +
	"\x10grpc/files.proto\x12\x04file\"}\n" +
	"\x0eUploadMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilesize\x18\x02 \x01(\x03R\bfilesize\x12\x1a\n" +
	"\bmimetype\x18\x03 \x01(\tR\bmimetype\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"'\n" +
	"\vUploadChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"v\n" +
	"\rUploadRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.file.UploadMetadataH\x00R\bmetadata\x12)\n" +
	"\x05chunk\x18\x02 \x01(\v2\x11.file.UploadChunkH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x84\x01\n" +
	"\x0eUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilesize\x18\x03 \x01(\x03R\bfilesize\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\"*\n" +
	"\x0fDownloadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"=\n" +
	"\rDownloadChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x12\n" +
	"\x04part\x18\x02 \x01(\x03R\x04part2~\n" +
	"\vFileService\x125\n" +
	"\x06Upload\x12\x13.file.UploadRequest\x1a\x14.file.UploadResponse(\x01\x128\n" +
	"\bDownload\x12\x15.file.DownloadRequest\x1a\x13.file.DownloadChunk0\x01B\x0eZ\f./api/filepbb\x06proto3"

var (
	file_grpc_files_proto_rawDescOnce sync.Once
	file_grpc_files_proto_rawDescData []byte
)

func file_grpc_files_proto_rawDescGZIP() []byte {
	file_grpc_files_proto_rawDescOnce.Do(func() {
		file_grpc_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_files_proto_rawDesc), len(file_grpc_files_proto_rawDesc)))
	})
	return file_grpc_files_proto_rawDescData
}

var file_grpc_files_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_files_proto_goTypes = []any{
	(*UploadMetadata)(nil),  // 0: file.UploadMetadata
	(*UploadChunk)(nil),     // 1: file.UploadChunk
	(*UploadRequest)(nil),   // 2: file.UploadRequest
	(*UploadResponse)(nil),  // 3: file.UploadResponse
	(*DownloadRequest)(nil), // 4: file.DownloadRequest
	(*DownloadChunk)(nil),   // 5: file.DownloadChunk
}
var file_grpc_files_proto_depIdxs = []int32{
	0, // 0: file.UploadRequest.metadata:type_name -> file.UploadMetadata
	1, // 1: file.UploadRequest.chunk:type_name -> file.UploadChunk
	2, // 2: file.FileService.Upload:input_type -> file.UploadRequest
	4, // 3: file.FileService.Download:input_type -> file.DownloadRequest
	3, // 4: file.FileService.Upload:output_type -> file.UploadResponse
	5, // 5: file.FileService.Download:output_type -> file.DownloadChunk
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_files_proto_init() }
func file_grpc_files_proto_init() {
	if File_grpc_files_proto != nil {
		return
	}
	file_grpc_files_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadRequest_Metadata)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_files_proto_rawDesc), len(file_grpc_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_files_proto_goTypes,
		DependencyIndexes: file_grpc_files_proto_depIdxs,
		MessageInfos:      file_grpc_files_proto_msgTypes,
	}.Build()
	File_grpc_files_proto = out.File
	file_grpc_files_proto_goTypes = nil
	file_grpc_files_proto_depIdxs = nil
}
